# Generated by Django 5.0.6 on 2024-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
