# Generated by Django 5.0.6 on 2024-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_created_by_alter_post_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='thread_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
